services:
  ioc:
    image: ghcr.io/cnpem/pmac-epics-ioc:$TAG
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: dynamic-link
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/pmac-epics-ioc
      args:
        REPONAME: pmac
        RUNDIR: /opt/pmac
        BUILD_STAGE_VERSION: latest
        RUNTIME_PACKAGES: libssh2-1-dev
